name: DEPLOY TO STAGING

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - uses: shivin9/bt3103-week-4@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
